# Generated by Django 4.1.6 on 2023-03-02 15:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('grade', models.CharField(blank=True, max_length=64, verbose_name='Grade')),
                ('registration_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Matricule')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Poste fixe')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Mobile')),
                ('role', models.CharField(choices=[('Chef', 'Chef'), ('Adjoint', 'Adjoint'), ('Secrétaire', 'Secretaire'), ('Autre', 'Autre')], default='Autre', max_length=32, verbose_name='Rôle')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='app.service')),
            ],
        ),
    ]
