# Generated by Django 4.1.6 on 2023-03-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse mail'),
        ),
    ]
