# Generated by Django 4.1.6 on 2023-02-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('Chef', 'Chef'), ('Adjoint', 'Adjoint'), ('Secrétaire', 'Secretaire'), ('Autre', 'Autre')], default='Autre', max_length=32, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='app.service'),
        ),
    ]
