# Generated by Django 4.1.6 on 2023-03-09 15:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agent_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='acronym',
            field=models.CharField(blank=True, max_length=32, verbose_name='Acronyme'),
        ),
        migrations.AddField(
            model_name='service',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse mail fonctionnelle'),
        ),
        migrations.AddField(
            model_name='service',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Poste secrétariat'),
        ),
    ]
