# Generated by Django 4.1.6 on 2023-02-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agent_role_alter_agent_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='police_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='police_rank',
            field=models.CharField(blank=True, max_length=64, verbose_name='Grade'),
        ),
    ]
