# Generated by Django 4.1.6 on 2023-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_agent_police_number_alter_agent_police_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='police_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
