# Generated by Django 4.1.6 on 2023-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_agent_police_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='rio',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='RIO'),
        ),
    ]
