# Generated by Django 4.1.6 on 2023-03-12 14:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_agent_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Adresse postale'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mail fonctionnel'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Poste standard'),
        ),
    ]
