# Generated by Django 4.1.6 on 2023-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_service_address_alter_service_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, help_text="Laisser vide si l'adresse est identique au service parent.", max_length=256, verbose_name='Adresse postale'),
        ),
    ]
