# Generated by Django 4.1.6 on 2023-03-02 08:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_agent_rio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='rio',
        ),
        migrations.AddField(
            model_name='agent',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Poste fixe'),
        ),
    ]
