# Generated by Django 4.1.6 on 2023-03-02 08:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_agent_rio_agent_mobile_agent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Mobile'),
        ),
    ]
