# Generated by Django 4.1.6 on 2023-03-02 08:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_agent_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Poste fixe'),
        ),
    ]
